spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcc?createDatabaseIfNotExist=false&useSSL=false
    name: tcc
    username: root
    password:
    initialization-mode: never
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
